site_name: Lalit's AI / ML Notebook
site_description: Notes and examples for data science, machine learning, and AI.
site_author: Lalit Prakash Vatsal
site_url: https://lprakashv.github.io/data-science-notes/
repo_name: lprakashv/data-science-notes
repo_url: https://github.com/lprakashv/data-science-notes
docs_dir: markdown-book
site_dir: site
exclude_docs: |
  notebooks/**/*.csv
  notebooks/**/*.tsv

plugins:
  - search
  - mkdocs-jupyter:
      execute: false
      ignore_h1_titles: true

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - fenced_code

theme:
  name: shadcn
  custom_dir: theme_overrides

nav:
  - Home: index.md
  - NumPy:
      - Introduction to NumPy: notebooks/numpy/numpy_intro.ipynb
  - Feature Engineering:
      - Feature Engineering: notebooks/feature_engineering/feature_engineering.ipynb
  - Recommendation Systems:
      - Recommendation: notebooks/recommender/recommendation.ipynb
  - Natural Language Processing:
      - Natural Language Processing: notebooks/nlp/nlp.ipynb
      - Advanced NLP: notebooks/nlp/advanced_nlp.ipynb
  - Deep Learning:
      - Neural Networks: notebooks/deep_learning/deep_learning_apps.ipynb
